name          'bjwschaap-puppet_mangabey'
version       '0.0.1'
source        'UNKNOWN'
author        'bjwschaap'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
